name: Bug Report
description: Report a bug or unexpected behavior in DotGnatly
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a NatsController with config...
        2. Call method X with parameters...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The server should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, the server...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - DotGnatly.Core
        - DotGnatly.Nats
        - DotGnatly.Extensions.JetStream
        - DotGnatly.Natives
        - Native Bindings (Go)
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Which .NET version are you using?
      options:
        - .NET 8.0
        - .NET 9.0
        - .NET 10.0
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you running on?
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: DotGnatly Version
      description: Which version of DotGnatly are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      render: csharp
      placeholder: |
        using var controller = new NatsController();
        var config = new BrokerConfiguration { Port = 4222 };
        await controller.ConfigureAsync(config);
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Trace
      description: Relevant logs, error messages, or stack traces
      render: shell
      placeholder: Paste logs here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This started happening after...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
